### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by henryhuang** [teambebop6/tb6-app-template#1]
- [ ] Role permission control

- [x] Basic admin CRUD

- [ ] REST api authentication
  - [x] JWT
  - [x] Add middleware for server api
  - [ ] If token is existed but expired, redirect to login page

- [ ] CI

**Comment by flaudre** [comment]
- [ ] Remove absolute paths from crud template

**Comment by flaudre** [comment]
- [ ] Add i18n
